### ISSUE TITLE
[BUG] Full screen on android phone or tablet and apple iPad tablet

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#111]
Might someone share, which browser (and if necessary settings) can be used to have a full screen display with the photos using the full screen.
I have tried on an old 5" **android phone**:
* **Chrome**: The url is always visible and the image isn't scaled to full screen
* **Fully Kiosk Browser** and **Full Screen Browser**: No url shown but image not scaled.

iPad: Not yet started to experiment.

**Comment by hajo62** [comment]
![IMG_6301](https://github.com/RouHim/this-week-in-past/assets/15800980/e5c8a366-5499-4d6b-9371-de17c1908088)

**Comment by RouHim** [comment]
Ok that could be a bug with the browser in landscape format, I'll have a look to see if something can be optimised.

**Comment by hajo62** [comment]
> browser in landscape format

That you don't waste time: Looks similar for portrait format: 
![IMG_6302](https://github.com/RouHim/this-week-in-past/assets/15800980/c77442cc-80f6-4f3d-8916-7236875bbce0)

**Comment by RouHim** [comment]
Hint to future me: Feels like an css issue. The image is scaled correctly by the backend but scaled down (not the full size) while displaying on the display.

**Comment by RouHim** [comment]
@hajo62 Thanks for testing, this is definitely a bug.

**Comment by RouHim** [comment]
@hajo62 Can you please test the container image tag: [18f11f](https://hub.docker.com/layers/rouhim/this-week-in-past/18f11f/images/sha256-be5d72191ee0cec9f8cf5fe58c9a6c6366705f2d0325d4fff38db9dadb719b27?context=repo)

**Comment by RouHim** [comment]
Cool, then I'm going to merge this.
