### ISSUE TITLE
FEATURE REQUEST: Make the file(s) that mark a folder to be excluded from indexing customisable

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#112]
Assumed I want to have two _screens_ showing different photos, I would run two containers: I.e. one for the living room and one for the office room. If the file marking folders to be excluded would be customisable, both instances could serve different images (without doubling the images).

**Comment by RouHim** [comment]
Hello, what is stopping you from simply selecting two different folders?

**Comment by RouHim** [comment]
But you can specify multiple folders in the RESOURCE_PATHS, so you could simply list them all for the office:
RESOURCE_PATHS=/photos/2023/10 - Team meeting,/photos/2022/10 - Office meeting

**Comment by hajo62** [comment]
> you could simply list them all

Thats a bit cumbersome because every time you create a new folder, you need to modify the `docker` cmds or the `docker-compose`-files.

I organise my photos by year and by event and meanwhile have 1146 folders...

**Comment by RouHim** [comment]
Would it help if this: https://github.com/RouHim/this-week-in-past#ignoring-folders would accept regular expressions?

**Comment by RouHim** [comment]
We have to decide on a practical solution, I don't really care as I don't use the feature. So I would leave you free creative space as long as it's not too complicated to implement.

**Comment by hajo62** [comment]
> free creative space

☺️

That would be my personal ranked list:

1. Configurable file name(s), **maybe** with a `.ignore` as default
2. Fixed file name different to the common `.ignore`. i.e. `.twipignore`
3. RegExp for directory names

**Comment by hajo62** [comment]
Tried with:
`      IGNORE_FOLDER_MARKER_FILES: .twipignore,.ignore`
and got the folling error in the logs:
`/resources/2000-2009/2001/2001.12 - Winterspaziergang" because it contains any of these files Err(NotPresent)`

When I remove `.ignore` everything seems to be fine.

**Comment by RouHim** [comment]
Thanks for testing, I pushed a fix. You can try again.

**Comment by hajo62** [comment]
Now it shows the marker files in the log.
`...because it contains any of these files Ok(".twipignore,.ignore")`

Tried with 
`IGNORE_FOLDER_REGEX: '.*ausblenden'` 
which results in 
`... because it is ignored by regular expression ".*ausblenden"`
as expected. In both cases, the number of images found is lower than the total images I have.

**Comment by RouHim** [comment]
Sounds good to me. I'll test it over the weekend and merge it when looks stable.

**Comment by hajo62** [comment]
Question: When a folder is ignored - i.e. by regexp or by marker file - are the sub folders ignored, too? 
Maybe a short note in the manual might be useful...

**Comment by RouHim** [comment]
Good point, if a folder is ignored all its sub elements, files and folders, are also ignored.
Could you pleas open a feature request for the documentation improvement?
