### ISSUE TITLE
[FEATURE] Manual iteration

### ISSUE THREAD

**Issue by horejsek** [RouHim/this-week-in-past#116]
Sometimes I want to enjoy photo for longer period, other times want to skip quickly to next one. What about adding option to tap or adding button to go to next one? And pause button? :-)

**Comment by hajo62** [comment]
Had the same idea, but though, you already made a lot ;)

Stop: stop slideshow toll play is pressed and auto-resume at midnight
Pause: Add the interval each time, the icon is clicked.
Skip (but not hide): Show next image
