### ISSUE TITLE
Random Photos displayed at year end

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#124]
Might there be an issue with the +/-3 days when the interval _covers two years_?

Today - 29.12.2023 - the interval would go to 01.01.2024 and I see random pictures displayed, although there are some photos taken in that interval.

**Comment by RouHim** [comment]
Jep I just discovered the same issue. Thanks for reporting.

**Comment by RouHim** [comment]
Wow, the problem really isn't easy to solve... I use a between query that checks whether the current date is between mm-dd(-3) and mm-dd(+3). But since the second part of the query with +3 results in 01-01, the query would be:
Is the photo between 29.12 - 01.01. This is not a valid query, as 01.01 is smaller than the start date.

**Comment by RouHim** [comment]
My first thought would be to query whether +-3 contains New Year's Eve, if so, simply display random images from the past year, do you have any other ideas @hajo62?

**Comment by hajo62** [comment]
Hhm, two _special cases_ with a sum of zwo _betweens_?

If today 29., 30. oder 31.12. then 
  all images between (today and today-3)
  plus all images between today and 31.12.
  plus all images between 01.01 and (3 - (31-day(today))).01.
fi

And a similar special case for 01.01. till 03.01.

Not sure, if that would works and could be done?!

I had a look in the log to check, if I'm on the latest greatest:
`[2023-12-30T10:27:03Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 0.0.0`

**Comment by RouHim** [comment]
Yeah I know, I just thought it would be funny to use this bug as an opportunity at the end of the year to do a kind of year in review :D

**Comment by hajo62** [comment]
It's not a bug, it's a feature?! 🤣

I would keep the function simple, even if it's a bit more complicated to realise, but it's you project.

**Comment by RouHim** [comment]
I just don't like the complexity/amount of the queries for this one case that affects 6 days a year. But you're right, we should focus on the essentials.

**Comment by RouHim** [comment]
@hajo62 If you like to test here is the related container image tag: [3dc2bf](https://hub.docker.com/layers/rouhim/this-week-in-past/3dc2bf/images/sha256-f073e0e4620cb678c8df98c6435b87ba6d09650798b63d73f8e563ae14acb9c0?context=repo)

**Comment by hajo62** [comment]
Hhm, not sure if I use the right image...
```
CONTAINER ID   IMAGE                                          
c13e5a5afdb3   rouhim/this-week-in-past:3dc2bf 
```

Saw images with _wrong_ dates.
```
 [2023-12-31T11:10:52]   taken: Some(2004-01-29T14:59:40) 
 [2023-12-31T11:12:52]   taken: Some(2018-08-05T12:01:40)  
 [2023-12-31T11:15:21]   taken: Some(2019-07-30T14:31:04)  
```

**Comment by RouHim** [comment]
Don't forget to refresh the browser 😉

**Comment by hajo62** [comment]
> Don't forget to refresh the browser 😉

Argh. Looks better immediately

Wünsche einen guten Rutsch.

**Comment by RouHim** [comment]
Danke ebenso 😁 I'll keep the ticket open until next year to ensure the issue is also next year gone.
