### ISSUE TITLE
Ignore jpg embedded thumbnails

### ISSUE THREAD

**Issue by TheManiacLives** [RouHim/this-week-in-past#126]
Currently the application is displaying embedded thumbnails from jpg sources.  It also displays full resolution versions from jpg files.  Would it be possible to exclude embedded thumbnails?

**Comment by RouHim** [comment]
Hello, checkout this sektion about ignoring folders: https://github.com/RouHim/this-week-in-past#ignoring-folders
If you have further questions, let me know.
