### ISSUE TITLE
Connecting multiple folders.

### ISSUE THREAD

**Issue by VlaK0r** [RouHim/this-week-in-past#127]
Hello!
Thank you for your hard work!
Please tell me, is it possible to connect multiple folders? 
For example, like this:
    volumes:
      - /path/to/pictures:/resources:ro # mount read only
      - /path2/to2/pictures2:/resources:ro # mount read only

Or is it necessary to do it in some other way?

**Comment by RouHim** [comment]
You could do it like this:
```

volumes:
- /path/to/pictures:/resources/1:ro
- /path2/to2/pictures2:/resources/2:ro
```

**Comment by VlaK0r** [comment]
And do I have to specify after that?
    environment:
      RESOURCE_PATHS: pictures,pictures2

**Comment by RouHim** [comment]
No, just keep it the default value ("/resources")

**Comment by VlaK0r** [comment]
Thank you very much!

**Comment by RouHim** [comment]
Does it work, can I close this ticket?

**Comment by VlaK0r** [comment]
> You could do it like this:

I jumped to conclusions.
It doesn't work that way. With that, that's how it works: 
```
    volumes:
      - /mnt/usbssd1/Samsung/Samsung A52/Camera:/resources/1:ro # mount read only
#      - /mnt/usbhdd/Photo:/resources/2:ro

```
And if so:

```
    volumes:
      - /mnt/usbssd1/Samsung/Samsung A52/Camera:/resources/1:ro # mount read only
      - /mnt/usbhdd/Photo:/resources/2:ro

```
It doesn't show anything at all, the screen is black.

**Comment by VlaK0r** [comment]
And again I jumped to conclusions)
Everything works, the photos were just processed for a long time, it was necessary to wait.
I apologize.

**Comment by RouHim** [comment]
Alright, great to hear that were able to solve the problem.
