### ISSUE TITLE
Adding new photos

### ISSUE THREAD

**Issue by VlaK0r** [RouHim/this-week-in-past#128]
Hello!
Thank you for your hard work!

Please tell me, when I add a new photo to a folder, do I need to restart the docker container or will it be added automatically?

**Comment by hajo62** [comment]
AFAIK, the indexing is done some minutes after midnight and it will find new images.

**Comment by RouHim** [comment]
Jep that's correct 👍.

**Comment by RouHim** [comment]
@VlaK0r Can I close this issue, or are there any open questions left?
