### ISSUE TITLE
Create an rss feed using XPathBridge in RSS-Bridge

### ISSUE THREAD

**Issue by VlaK0r** [RouHim/this-week-in-past#129]
Hello!
Thank you for your hard work!

I'm trying to create an rss feed using XPathBridge in RSS-Bridge
`https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/XPathBridge.php`

I can't figure out what to insert in the "Item image selector" field
I tried it like this - `.//div[@id="background-image"]/@style`, but it doesn't work.

Help please.

**Comment by RouHim** [comment]
Hey ho, sorry but there is no API endpoint that delivers an image directly by an HTTP URL. But if you have the need for it, feel free to file a new feature request for it. 
If so, please describe exactly what you expect from the new API endpoint.
