### ISSUE TITLE
No images from last year displayed?

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#130]
Might there be a bug with images from last year?

I have some images taken on 02.02.2023, but it looks like they aren't displayed (today is 04.02.2024).

Updated to 1.20.2 today. 
Meanwhile 240 images - 125 uniq - have been displayed, but none from 2023.

**Comment by RouHim** [comment]
Hello,
so your issue is that there are no images displayed from this year?

**Comment by hajo62** [comment]
Not sure if nothing from **last** year.

I've recognised that last days, because I have images of an anniversary on 02.02.2023 (with correct metadata and no ignore) and haven't seen an images of that folder...

I sorted the log to doublecheck, but nothing from 2023.

```
docker-compose logs this-week-in-past | sed -e 's/Z DEBUG.*path:/] |/g' -e 's/, content_type.*taken: / | taken: /g' -e 's/, location.*//g' | grep taken | awk -F '|' '{print $2,$4,$3}' | grep -e "..........T........" | cut -d '"' -f2 | sort
```

**Comment by RouHim** [comment]
I've just added a new api endpoint, which you can query yourself #133. It lists all images which could be shown in this week, incl. the metadata.

**Comment by hajo62** [comment]
Still nothing from 2023, but...

Found a typo in my RESOURCE_PATHS. -  **Sorry for the circumstances**

BUT: Thanks for the new endpoint. I was thinking to have something like that, but did not open an RFE because it is _just_ something nice to have ;) 

Maybe add a "Found n memories." at the top in the output of the new endpoint?
