### ISSUE TITLE
[FEATURE] Some pictures are displayed multiples times a day - How are the images selected to be shown?

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#138]
I wonder, how you randomise the displayed images and if it is the intended use, that roughly 15-20% images are displayed more than once a day although there are more than enough images not displayed.

In numbers:
Yesterday I had 486 images in the +/- 3 day range found by your algo.
251 images had been displayed but only 
207 uniq images.

I assume, you fill a _list_ and randomly pick images from that _list_?

If so, might be filling a list, once randomise the order of that list and than pick images one by one be an idea to avoid twice (or more times) displaying the same image be an idea? When reaching the end of the list, just start at the beginning or do a new randomisation.

Caveat: I have no idea if such a list is hold on the server or in the browser a client side? If on server side, all clients would display the images in the same order.

**Comment by RouHim** [comment]
That is exactly what I do. I randomize on server side and the web client receives this list. The client then iterates the randomized list one by one.

**Comment by RouHim** [comment]
I think what breaks the random factor is the value of REFRESH_INTERVAL. Every time this is reached, a new random list is generated.

**Comment by hajo62** [comment]
Is it necessary to generate a new list every time?

What about having a kind of hash or time stamp for the server side list and regenerate the client side list only if that hash has changed or the time stamp is younger that on client side.

**Comment by RouHim** [comment]
Thats the way how to client ensures to get new images from the server side. If this does not fit your needs, you could just turn up the interval.  This should fix the issue.
It is designed this way, as always, to keep it maximum simple :)

**Comment by hajo62** [comment]
> (Just keep in mind that turning up the interval, might increase the detection latency for new images)

Had that in mind. Therefore I think you've chosen a good default value and increasing that value would just start later with showing duplicates.

But nevertheless and without knowledge of how you realised your project: If it is possible to fetch a time stamp for the server side images list, an additional compare should make the design not too complicated.

**Comment by RouHim** [comment]
Yeah I know, but I'm basically always out of time, thus if things are not really broken I most likely will not touch them :D
Nevertheless I'm happy for any PR ;)

**Comment by hajo62** [comment]
It's okay to _reuse_ this question as an RFE?

Solving this might be good for a rainy day...

By the way: Love that app and found wrong or missing meta data in very old fotos.

**Comment by RouHim** [comment]
Great to hear, yeah sure, go for it!

**Comment by hajo62** [comment]
> Solving this might be good for a rainy day...

Looks like there are some rainy days ahead 🤣
<img width="156" alt="image" src="https://github.com/RouHim/this-week-in-past/assets/15800980/ad2541de-1568-4670-a908-e0c09518928a">

OFFTOPIC:
I assume, you run your Home Assistant (as well as this-week-in-past) on docker? 
If so, do you have a sensor or similar, which shows docker images, which have an update available?

**Comment by RouHim** [comment]
I'm provisioning my local infrastructure at home via truenas scale. But maybe this is what you are looking for:
https://github.com/containrrr/watchtower

**Comment by hajo62** [comment]
> I think what breaks the random factor is the value of REFRESH_INTERVAL

Not sure, if that works. 
Changed the url to ... which I understand to 12 h till refresh, but still have lots of duplicates.
`http://<url>?WEATHER_ENABLED=false&REFRESH_INTERVAL=720`

**Comment by hajo62** [comment]
Regarding your suggestion to go with longer refresh intervals: I assume, that the refresh isn't the cause.
Although, I've set the interval to 12h, some images are displayed often a day. Here stripped log parts...
```
 [2024-09-04T08:36:06]   taken: Some(2007-09-01T18:16:56)  "/resources/.../Picture 052.jpg" 
 [2024-09-04T14:04:32]   taken: Some(2007-09-01T18:16:56)  "/resources/.../Picture 052.jpg" 
 [2024-09-04T14:36:32]   taken: Some(2007-09-01T18:16:56)  "/resources/.../Picture 052.jpg" 
 [2024-09-04T15:26:32]   taken: Some(2007-09-01T18:16:56)  "/resources/.../Picture 052.jpg" 
```
or
```
 [2024-09-04T06:32:35]   taken: Some(2007-09-01T12:35:51)  "/resources/.../Picture 013.jpg" 
 [2024-09-04T14:28:32]   taken: Some(2007-09-01T12:35:51)  "/resources/.../Picture 013.jpg" 
 [2024-09-04T15:56:34]   taken: Some(2007-09-01T12:35:51)  "/resources/.../Picture 013.jpg" 
```

**Comment by RouHim** [comment]
That's Ok, when there are to less images to fill the 12 hours. Then there are images that will be shown multiple times, because the slideshow restarts automatically at the beginning.

**Comment by hajo62** [comment]
I thought so, too, but: The app found about 250 images, each displayed 2 mins, which should be enough for more than 8 hours.
And the images repeated after roughly 6h, 30 min and again 50 mins.

**Comment by joe128** [comment]
I noticed the problem when RANDOM SLIDESHOW is enabled. Then a new random image is fetched for each “slideshowTick”.
I think it would be better in this case if "all resources" were loaded and played.
For my use case I create a set of images for an event (e.g. a birthday) that has taken place on different days (greater than +/- 3 days) over the years, which makes the RANDOM SLIDESHOW config necessary.

**Comment by RouHim** [comment]
Please, if you think you have found an issue:
1) Make your issue reproducible with the smallest possible set of data 
2) If you think you REALLY found an issue: Create an issue
3) Share your data / config / steps to reproduce with me (Also possible via email)

If you need space to discuss, please do it here: https://github.com/RouHim/this-week-in-past/discussions/

@hajo62 Same goes for #148 

I don't want to sound rude, but it's like always. This is a hobby project that I'm doing besides family / work, so I have not much time. That's why I need your help if you have found a mistake.

@joe128 I'm pretty sure the random config is pretty buggy. So if you found something, please follow step 1-3 ;)

**Comment by hajo62** [comment]
> 3\. Also possible via email

Where do I find your mail address to send test data?
