### ISSUE TITLE
Image from yesterday selected

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#139]
Looks like your algo does also pick images from the same year. 
Saw an image taken and imported yesterday.

**Comment by RouHim** [comment]
Yes that's on purpose

**Comment by hajo62** [comment]
Hhm, to be honest: No ;) but nevertheless okay for me.

It's really a minor thing - Typically I haven't moved the images on the arrival day or a day later so that it took several month till I saw that happen a first time.

But I think most providers start with memories later than the last some days.

**Comment by RouHim** [comment]
I really like the feature thus I'll keep it this way. But lets convert this to a feature request if this is a thing for you?

**Comment by hajo62** [comment]
Works as designed.
