### ISSUE TITLE
Change env USER

### ISSUE THREAD

**Issue by RPonturo** [RouHim/this-week-in-past#151]
Hi, 

I'm trying to use the variable USER to change the UID but without success.

The app run always with userID 1337. 

How can i change it?

Using in Synology DSM - Container Manager

Thanks
Raffaele

**Comment by RouHim** [comment]
Hello Raffaele,
did you try overriding the user?

you can use the --user option in docker run or the user field in docker-compose. 
Using docker run:

```bash
docker run -u <UID>:<GID> <image>
```

Replace <UID> with the desired user ID, <GID> with the group ID.

Using docker-compose:

In your docker-compose.yml file, specify the user field:

```bash
services:
  your_service:
    image: <image>
    user: "<UID>:<GID>"
```

**Comment by RouHim** [comment]
Great that I could help.
