### ISSUE TITLE
Ignore hidden folder starting with .

### ISSUE THREAD

**Issue by RouHim** [RouHim/this-week-in-past#60]

**Comment by hajo62** [comment]
Maybe hide folder via a _switch file_?
If i.e. `.ignore` is included in folder, the folder should be hided...

**Comment by RouHim** [comment]
I am still unsure how best to implement this. Many users do not want to or cannot manipulate their data. So I have to think of a comfortable way to do that. It is important to me that there is only one way to do this, so that the handling of hiding folders is not confusing.

**Comment by hajo62** [comment]
I understand. But people who are comfortable running your code should be able to execute a `touch .ignore`...
Think about a folder with private images which should not occasionally appear in memories but you don't want to hide those folders for other use cases... 

PiGallery2 has an option like that and looks like people are fine with that.

**Comment by RouHim** [comment]
Ok I see there is a demand for that :) So I think will hop on with:
`.ignore` - to ignore a folder.
A new variable to set a folder name exclusion list. 
So basically like PiGallery2 does.
Thanks for the hint.

**Comment by hajo62** [comment]
Thx.
And by the way. Found your stuff yesterday and directly started to like it ;)

**Comment by RouHim** [comment]
Great to hear, thanks :)
