### ISSUE TITLE
Never stops indexing? 

### ISSUE THREAD

**Issue by dannongruver** [RouHim/this-week-in-past#64]
I refreshing web page and keep getting a "No images found" javascript alert/message box. 

Am I doing something wrong? Here's how docker start and output:
![image](https://user-images.githubusercontent.com/1030475/207122915-3c0d00d1-0bdf-4449-803d-1ac8ed7ef4c8.png)

**Comment by RouHim** [comment]
Hey @dannongruver,
the index is already done, but, as the 5th line tells us, there was no resources found:
`Found 0 resources`

It looks like `~/nextcloud/Photos` does not exists or does not provides any photos.

**Comment by dannongruver** [comment]
Hmmm…the ~/Nextcloud/photos folder exists & has photos (jpg). Also it looks like I named the mountpoint correctly via “docker run” command (see top of screenshot). Does the mount in the docker run command look correct? I have another photo app also pulling from this same folder successfully.

**Comment by RouHim** [comment]
You can try to set the path in the container explicitly. Just add `-e RESOURCE_PATHS="/resources"` to the docker run command. It may be also worth to try executing the docker run command without the `:ro` option.

**Comment by dannongruver** [comment]
Same error

![image](https://user-images.githubusercontent.com/1030475/207135649-8b14cfbe-8d5f-412c-b3d1-68ebab9d3630.png)

**Comment by RouHim** [comment]
Too bad :( which operating system and hardware are you using? Maybe it is platform related?

**Comment by dannongruver** [comment]
Strange. Other docker containers mount fine using same photos path.

this is on mint Linux 22 and intel x64


Oh well, would’ve really liked to have a slideshow Nextcloud images on old iPad 😮‍💨

**Comment by RouHim** [comment]
Ok, I'm running the image in kubernetes myself, I'll check a little closer and get back to you with any new findings. I will leave the ticket open until then.

**Comment by RouHim** [comment]
Short update: There is currently an issue with the container build.
To fix this, it takes a bit more time.

**Comment by RouHim** [comment]
@dannongruver 
Can you please try the `test` image tag: `rouhim/this-week-in-past:test`.

**Comment by RouHim** [comment]
No response so I guess it is closed.

**Comment by dannongruver** [comment]
Apologies for delay (holidays). Yes, it is working now and finds the photos. Thank you!

**Comment by RouHim** [comment]
Great to hear 👍
