### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by luandro** [RouHim/this-week-in-past#81]
I keep getting:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/filesystem_client.rs:49:42
```

Pictures are under the same user as Docker is being executed.

**Comment by RouHim** [comment]
Hello, thanks for the error report, as the message suggests there seems to be a problem with the permissions. Please give me some information about: 
* Your operating system 
* What your docker command looks like 
* What permissions your folder has

**Comment by luandro** [comment]
Pulled latest. Here's the Docker command:

```
docker run -p 8080:8080 \
        -v /home/user/images/:/resources \
        -e SLIDESHOW_INTERVAL=10 \
        -e RUST_BACKTRACE=full \
        rouhim/this-week-in-past
```

It seems it's not permission error anymore with the latest version. I'm running on Arch linux, Marnjaro, and permissions are set to the same user running Docker.

Here's the ouput:
```
[2023-05-03T11:51:21Z INFO  this_week_in_past::scheduler] Begin resource indexing
[2023-05-03T11:51:21Z INFO  this_week_in_past::scheduler] Indexing resources, this may take some time depending on the amount of resources...
[2023-05-03T11:51:21Z INFO  this_week_in_past]  🚀 Launching webserver on http://0.0.0.0:8080 🚀 
thread '<unnamed>' panicked at 'Failed to read file /resources/PXL_20230214_192953972.jpg', src/filesystem_client.rs:53:29
stack backtrace:
   0:     0x7f1dadaac830 - <unknown>
   1:     0x7f1dad91a42e - <unknown>
   2:     0x7f1dada867f4 - <unknown>
   3:     0x7f1dadaade3f - <unknown>
   4:     0x7f1dadaada3f - <unknown>
   5:     0x7f1dadaaeacd - <unknown>
   6:     0x7f1dadaae5a4 - <unknown>
   7:     0x7f1dadaae50c - <unknown>
   8:     0x7f1dadaae4e1 - <unknown>
   9:     0x7f1dad7744f2 - <unknown>
  10:     0x7f1dad7a61a4 - <unknown>
  11:     0x7f1dad89326b - <unknown>
  12:     0x7f1dad853f50 - <unknown>
  13:     0x7f1dad89bd2f - <unknown>
  14:     0x7f1dad7fbfa0 - <unknown>
  15:     0x7f1dad805568 - <unknown>
  16:     0x7f1dadaafa75 - <unknown>
```

**Comment by RouHim** [comment]
Can you please check if this file (PXL_20230214_192953972.jpg) is somehow corrupted?

**Comment by luandro** [comment]
It doesn't seem like it.

**Comment by RouHim** [comment]
Ok then let's dig into it. First we should rule if it is docker related or not, so there is a way to run the application without docker:

1.  Download the latest ([release](https://github.com/RouHim/this-week-in-past/releases))
2. Create a data directory:
```bash
mkdir data
```
3. Execute the application:
```bash
RESOURCE_PATHS=/home/user/images/ \
DATA_FOLDER=data \
SLIDESHOW_INTERVAL=10 \
./this-week-in-past
```

**Comment by RouHim** [comment]
@luandro ping, is this still an issue? Otherwise I will close this ticket tomorrow.
