### ISSUE TITLE
[Feature] Add A Random Env Variable

### ISSUE THREAD

**Issue by panzerwaffen** [RouHim/this-week-in-past#89]
Would it be possible to add a random variable instead of just looking for pictures for a particular week.  It would be for a relatively small directory of photos sub 1k.  Your container basically checks all the boxes and I know others are looking for something similar.   Thank you

**Comment by RouHim** [comment]
Hey @panzerwaffen,
thanks for your report.
Sounds like a good idea, I'll keep this ticket open to track the development progress.

Greetings

**Comment by RouHim** [comment]
@panzerwaffen the feature was just merged and can be tested. Any feedback is welcome!

**Comment by RouHim** [comment]
Your name suggests that you are german, so I'll continue on german ;)

Mein Beileid zuerst einmal, ein Haustier ist meist ein richtiges Familien Mitglied und es schmerzt sehr es zu verlieren. Von daher freue ich mich das ich euch so bei der Erinnerung helfen kann.
Du kannst mir ja einfach eine email an: rouven@himmelstein.info schreiben.
Gruß
