### ISSUE TITLE
Image displayed with wrong date and wrong location

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#95]
I wonder which information is used for location and data. I assume the metadata embedded in the image.

I saw an image displayed to be taken on 15.09.2020 in Adiri (Libyen), but in reality the image was taken in November 2018 at Gran Canaria. I checked the data with XNView MP where EXIF Aufnahmedatum is 18.11.2018 and GPS is shown to be Gran Canaria.

Transferred blured image for debugging purpose. FIle and EXIF modification date is now, but EXIF Aufnahmedatum and GPS is original.

I assume, that's the image but of cause, maybe your tool found a duplicate which I'm not aware of...

Pls. give a note, when downloaded the image, that I can remove the link above...

**Comment by RouHim** [comment]
Thanks for your report, I've downloaded the image.

**Comment by hajo62** [comment]
I assume not connected, but I don't want to flood with issues.
Just got this
```
this-week-in-past  | thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))', src/resource_store.rs:130:14
this-week-in-past  | stack backtrace:
this-week-in-past  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
this-week-in-past exited with code 139
```

I have started the app via docker-compose:
```
...
    environment:
      BIGDATA_CLOUD_API_KEY: xxx
      WEATHER_ENABLED: true
      WEATHER_LANGUAGE: de
      OPEN_WEATHER_MAP_API_KEY: xxx
      RESOURCE_PATHS: /resources/2022,/resources/2021,/...
      RUST_BACKTRACE: 1
      TZ: Europe/Berlin
      PUID: 33
      PGID: 33
```
A chance to provide helpful debug info?

**Comment by RouHim** [comment]
I actually found a bug in gps date / lat, long reading. Thank you for reporting that.
The other thing is also interesting. 
Was you viewing the "website" while the scanning / indexing was in progress?
If so, there might be also a bug.

**Comment by RouHim** [comment]
I just pushed a fix for the first bug reported from you, thank for the test photo, it helped me a lot.
I'll most likely merge this fix this evening. I'll keep you up-to-date.

**Comment by hajo62** [comment]
> Was you viewing the "website" while the scanning / indexing was in progress?

I don't think so. AFAIK the webpage stays black till the scan is done...

But meanwhile I made the debug from `1` to `full` and when I started the _app_ I got this:

```
this-week-in-past  | [2023-09-14T13:31:08Z INFO  this_week_in_past::scheduler] Found 20121 resources
this-week-in-past  | [2023-09-14T13:31:09Z INFO  this_week_in_past::scheduler] Purging resources store
this-week-in-past  | [2023-09-14T13:31:10Z INFO  this_week_in_past::scheduler] Cleanup cache
this-week-in-past  | [2023-09-14T13:31:11Z INFO  this_week_in_past::scheduler] Inserting new resources
this-week-in-past  | [2023-09-14T13:31:14Z INFO  this_week_in_past::scheduler] Cleanup database
this-week-in-past  | thread 'actix-rt|system:0|arbiter:1' panicked at 'Insertion of 5c28f8d86e713cccf4179a189d5de970_2560_1415 failed', src/resource_store.rs:83:33
this-week-in-past  | stack backtrace:
this-week-in-past  |    0:           0x6fa498 - <unknown>
this-week-in-past  |    1:           0x570894 - <unknown>
this-week-in-past  |    2:           0x6da06c - <unknown>
this-week-in-past  |    3:           0x6fbb48 - <unknown>
this-week-in-past  |    4:           0x6fb2e0 - <unknown>
this-week-in-past  |    5:           0x6fc328 - <unknown>
this-week-in-past  |    6:           0x6fbd8c - <unknown>
this-week-in-past  |    7:           0x6fbd00 - <unknown>
this-week-in-past  |    8:           0x6fbcf4 - <unknown>
this-week-in-past  |    9:           0x408d6c - <unknown>
this-week-in-past  |   10:           0x4fc830 - <unknown>
this-week-in-past  |   11:           0x4ed764 - <unknown>
this-week-in-past  |   12:           0x4e4ab4 - <unknown>
this-week-in-past  |   13:           0x4231a4 - <unknown>
this-week-in-past  |   14:           0x4296a4 - <unknown>
this-week-in-past  |   15:           0x431ad8 - <unknown>
this-week-in-past  |   16:           0x4d2af8 - <unknown>
this-week-in-past  |   17:           0x70f354 - <unknown>
this-week-in-past  |   18:           0x537160 - <unknown>
this-week-in-past  |   19:           0x535acc - <unknown>
this-week-in-past  |   20:           0x534694 - <unknown>
this-week-in-past  |   21:           0x6fd1d4 - <unknown>
this-week-in-past exited with code 139

```

**Comment by RouHim** [comment]
You can also set RUST_LOG=debug.

Ok I have a feeling what went wrong...

How much folders did you set in the "RESOURCE_PATHS" variable?
Can you please try to set only one, and check if the error persists?

**Comment by hajo62** [comment]
> Can you please try to set only one, and check if the error persists?

Changed to one folder... BUT: The problem does not occur every time. Therefor not sure, when it is _safe_ ;)

It now ran stable for one hour.

**Comment by RouHim** [comment]
I've pushed a test docker image tag: `16957a`
Would be nice if you could test, if this test version fixes your location / date issue.

**Comment by hajo62** [comment]
I assume, you ask me to pull like...  -  which I did right now
```
version: '3.9'
services:
  this-week-in-past:
    image: rouhim/this-week-in-past:16957a
```

But do you have an idea how to test? 
The images had been shown because of the bug. Now I should not see them anymore. Could take a while to be reasonably sure. And if the aren't shown anymore, I can't check the location...

**Comment by RouHim** [comment]
Maybe copy that one image that was broken to a new folder, then only set this new folder in RESOURCE_PATHS

**Comment by hajo62** [comment]
Okay, did so.
**GPS**: Now the location is named **San Bartolomé de Tirajana** which is correct. But I need to google to check if it is near Maspalomas (which is the common name for that place). 
Doublechecked that place with the API... 
-> Solved and (now) works like designed.

Maybe extending the displayed information by `principalSubdivision`? Not sure, if this is always useful, but in that case it would state _Las Palmas_, which is more common.

**Date**: The date is now display correct, although I wonder, why I see pictures taken in November.
-> Solved

Pls. ping me, if you publish a new version; otherwise I would stay on the tagged one 😉

**Comment by RouHim** [comment]
> The date is now display correct, although I wonder, why I see pictures taken in November.

To cite myself:
> If no images from the calendar year are found, random images are displayed.

> Pls. ping me, if you publish a new version; otherwise I would stay on the tagged one 😉
Ok, this is a temporary tag, but if there is a final release I'll let you know.

>  Ups, now there is an image shown without a place, although it has embedded GPS data. Can share the image, if useful...
Yes please

**Comment by hajo62** [comment]
Okay, regarding the test I did... Got the RTFM 😇

BUT, now I have nearly 20k images in several resources (folders) and still see random images, although there are enough memories.

One [example](https://nc.hajo62.duckdns.org/s/pRDTf8cRMMbkJTS) for an image where no location had been displayed.

For your performance statistics: RPi4 with 8 GB and 1 TB ssd:
```
this-week-in-past  | [2023-09-15T07:28:30Z INFO  this_week_in_past::scheduler] Found 19877 resources
this-week-in-past  | [2023-09-15T07:28:30Z INFO  this_week_in_past::scheduler] Purging resources store
this-week-in-past  | [2023-09-15T07:28:30Z INFO  this_week_in_past::scheduler] Cleanup cache
this-week-in-past  | [2023-09-15T07:28:31Z INFO  this_week_in_past::scheduler] Inserting new resources
this-week-in-past  | [2023-09-15T07:28:33Z INFO  this_week_in_past::scheduler] Cleanup database
this-week-in-past  | [2023-09-15T07:28:38Z INFO  this_week_in_past::scheduler] Job done in 181s!
```

**Comment by RouHim** [comment]
Nice, thanks for your help :)

I will nevertheless take a look at the broken picture. 
Thanks for sharing the log :+1: 
It is always exciting to see how the programme performs on different devices.

**Comment by hajo62** [comment]
> Nice, thanks for your help :)

Very welcome. Like your app.
Found 33011 resources -> Job done in 289s! - Same Pi.

---

Looks like you run **HomeAssistant**, too.
An idea how to embed the app output (see displayed images) to a lovelace widget?

**Comment by RouHim** [comment]
> One example for an image where no location had been displayed. (But don't spend to much time in analyzing the image. Might have been a kind of interference - app restarted and browser not refreshed.)

Great, found another little issue there :) Thank you very much!

>  An idea how to embed the app output (see displayed images) to a lovelace widget?


I'm using this: https://www.home-assistant.io/dashboards/iframe/

**Comment by RouHim** [comment]
The fix is merged and should be available on the "latest" tag in about 10 mins.

**Comment by RouHim** [comment]
Also the hidden folder feature is out.

**Comment by hajo62** [comment]
Pulled the new image. How would I check, that this is the right version?
Maybe you could extend the log...

1) Again had a:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'Insertion of f17babb634fb545e6792fcbd7fff1231_2560_1415 failed', src/resource_store.rs:83:33
stack backtrace:
   0:           0x6fa498 - <unknown>
   1:           0x570894 - <unknown>
   2:           0x6da06c - <unknown>
   3:           0x6fbb48 - <unknown>
   4:           0x6fb2e0 - <unknown>
   5:           0x6fc328 - <unknown>
   6:           0x6fbd8c - <unknown>
   7:           0x6fbd00 - <unknown>
   8:           0x6fbcf4 - <unknown>
   9:           0x408d6c - <unknown>
  10:           0x4fc830 - <unknown>
  11:           0x4ed764 - <unknown>
  12:           0x4e4ab4 - <unknown>
  13:           0x4231a4 - <unknown>
  14:           0x4296a4 - <unknown>
  15:           0x431ad8 - <unknown>
  16:           0x4d2af8 - <unknown>
  17:           0x70f354 - <unknown>
  18:           0x537160 - <unknown>
  19:           0x535acc - <unknown>
  20:           0x534694 - <unknown>
  21:           0x6fd1d4 - <unknown>
```

2) Got an image displayed to be taken at 02. October, although EXIF says 19. September.
Can share, if useful.

**Comment by hajo62** [comment]
pulled to early ;)

Now I see log messages like `because it contains a .ignore file`
