### ISSUE TITLE
[FIX] Use per day comparision ( +/- 3 days ) instead of week of year

### ISSUE THREAD

**Issue by hajo62** [RouHim/this-week-in-past#99]
I would assumed, today (16.09.) is the middle of a virtual week resulting in images taken in the interval 13.09. - 19.09., but that does not fit to 20.09. which I saw images from... 
Reading your description, you use week meaning you go via Calendar week...

This week -> KW 37 
In 2018 10.09. till 16.09, which would explain, that images taken 18.09.2018 aren't show, although images 20.09. in other years might be shown.

If so, that is a little confusing for me. And maybe for others, too? 
Especially because some years have 52 and others 53 calendar weeks, which result in images nearly shown never... 
I.E. Ski-vacation or Sylvester 2020 (28.12.2020-03.01.2021) would be shown next time in 2026. 
Similar for fixed dates (birthday, christmas, ...): At my birthday I would see photos taken in 2020 or 2022, but not those taken 2021.

If going via calendar week, might my suggestion - week as 3 days before and after _today_ - be an option to be realized and configured via settings.

**Comment by RouHim** [comment]
Yes you are right, its the calendar week. There is no special reason for that, expect it was easy to implement. But I'm with you, there is room for improvement :) Your suggestion with `week as 3 days before and after today` should also be implementable with reasonable effort.

**Comment by hajo62** [comment]
Just pulled a new image.
Whow. Looks like already implemented 😀

**Comment by RouHim** [comment]
Jep, there is a testing docker tag `c3bdf0`.
But I have to test it a bit more ;) Not fully polished yet.

**Comment by hajo62** [comment]
Just pulled again. Assume, I use the latest...
Right now, I saw an image taken 25.09.2022, which I wouldn't expect to be shown anymore?

**Comment by RouHim** [comment]
Yes I have observed the same behaviour, it seems to overlap a single day in some cases. 
I'll dig into this...

**Comment by RouHim** [comment]
@hajo62 Can you please test the docker tag `9f6d72`. Looks good for me.

**Comment by hajo62** [comment]
And saw an image taken 23.09.2018 and on of 24.09.2002

Assuming the right version, because logs says: `👋 Welcome to this-week-in-past version 0.0.0`

**Comment by RouHim** [comment]
The version is good because it is a debug version.
I forget to update you, I've implemented the first day of week until last day of week thing. So 18-24 for this week. 

Does this implementation is ok for you?

**Comment by RouHim** [comment]
Ok I think you misunderstood me. Until Sunday would be basically always the same pictures from the last years from Monday to Sunday respectively. Until then the new week begins. So I have a kind of time frame that always moves by a week.

**Comment by hajo62** [comment]
> would be basically always the same pictures

Same picture for the whole week... 
That's fine if you would use the app every now and than.
If one would use the app i.e. in a Home Assistant dashboard or on a picture frame **I think**, a slight change of pictures shown every day would be more interesting than 7 days the same _collection_ (especially when during that week not so many pictures had been taken in the past) an than all changed to a new _collection_...

What I like most on that memories is the "Do you remember. Today 5 years ago we did this and that". 

Therefor - if I could realize an app like that, what I unfortunately can't - I would go with a +/- 3 days and weight the frequency with a kind of Gauss-function - possibility a picture is displayed. (I.E. 8 points for today, 6 points for +/- 1 day difference, 3 points for +/- 2 days and 1 point for +/- 3 days...)
But to be honest - I think that's a way more complicated and therefore maybe slightly over-engineered... 

And as I said: Just my thoughts. It's your app which I really appreciate.

Before I get what you've asked me to do: Look's like it does what you have described. Haven't recognized a wrong picture till now.

**Comment by RouHim** [comment]
Good point, I have round about 100k photos to display, thus not much duplicates I discover in a week. But I see your point, with a lower amount of pictures your algorithm would be better. I honestly do not have a strong opinion which photo should be shown best at which time. So your suggestion sounds good to me. What I can't promise is the gauss distribution for the random function, because I heavily rely on a the sqlite query language which I do not know very good; I have to check this.

**Comment by RouHim** [comment]
I've implemented a custom weighted random that moves images that have a closer distance to today at the beginning of the slideshow. Feel free to try it in about 10 minutes.

**Comment by hajo62** [comment]
Just pulled.

Ah, you calculate a slideshow for all images fitting in the time intervals, when the app starts and every beginning of a day?

Another option might also be to _dice_ when an images is found to be shown next and _throw it away_ - and sort it at the end of the list - with a probability somewhat over-proportional to the days interval.

**Comment by RouHim** [comment]
Thanks a lot for your input; I like the 3 days + / - way more and more. Should be on `latest` tag in the next minutes.

**Comment by hajo62** [comment]
> I like the 3 days + / - way more and more.

And I was already afraid that I would overwhelm you with my suggestions.

**Question**: I saw an image from 15.09. which today is outside the +/- 3 days.
Is there a _recalculation_ of the images for today and when is it done? I have started the app yesterday evening.

**Comment by RouHim** [comment]
Make sure that you run version: 1.15.0, if not, just pull the latest tag again.

**Comment by hajo62** [comment]
okay. Still on the build from yesterday evening...

Every now and than I see this, when stopping the container:
```
docker-compose stop this-week-in-past
[+] Running 0/1
 ⠿ Container this-week-in-past  Error while Stopping                                                                                                                                                                          24.0s
Error response from daemon: cannot stop container: 425afc5b2dec2cf4d2a4902c13fc882ef58123833a96b0e6eca1f7636d945426: container 425afc5b2dec PID 107396 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes
```

**Comment by RouHim** [comment]
Ok that surprises me, I am actually doing a very simple check +- 3 days. I'll check again. The error may come because the scheduler in the program takes about 30s to shut down. Maybe the docker client marks the process as a zombie even though it is still shutting down. In any case, it should be gone after some time.

**Comment by hajo62** [comment]
Yes. The container is stopped. 
And this message does not come every stop. Only sometimes.

**Comment by hajo62** [comment]
When do you do the recalculation of the slideshow? Fixed time or 24h after the app had been started or ...?
8:20 o'clock and an image taken on 18.09. had been shown, which is -4 days, but 10 mins later, I saw an image taken on 25.09., which let's me assume, a recalculation had occurred?

- Have you optimized something on garbage collection or memory consumption? In the past I saw roughly 750 MB mem usage, which is now below 300 MB.

- Is the app a single thread? I have limited resources to 1 CPU and 1 GB, and looks like the performance is (nearly?) the same. - 25522 resources in 123 seconds on Pi 4

**Comment by hajo62** [comment]
When do you do the recalculation of the slideshow? Fixed time or 24h after the app had been started or ...?
8:20 o'clock and an image taken on 18.09. had been shown, which is -4 days, but 10 mins later, I saw an image taken on 25.09., which let's me assume, a recalculation had occurred? - I'm using 1.15.2.

- Have you optimized something on garbage collection or memory consumption? In the past I saw roughly 750 MB mem usage, which is now below 300 MB.

- Is the app a single thread? I have limited resources to 1 CPU and 1 GB, and looks like the performance is (nearly?) the same. - 25522 resources in 123 seconds on Pi 4

**Comment by hajo62** [comment]
Ah, sorry. 
Thought you did some fixes in this area, because last time it was 1.15.0 and now I run 1.15.2

**Comment by RouHim** [comment]
I ran a software called renovate that automagically bumps dependency versions to keep track with bugs and CVEs of thrid party parts of the software.

**Comment by hajo62** [comment]
> Hey, I was not able to analyze the problem yet sorry.

Shouldn't the issue than be reopened?

(Might you share your Lovelace code, how you _embedded_ your app into home assistant?)

**Comment by RouHim** [comment]
Yes of course!

**Comment by RouHim** [comment]
So I've invested some time to reproduce the issue and wrote some tests. But ... I can't. Are you sure that you are on the latest version?

**Comment by hajo62** [comment]
```
this-week-in-past  | [2023-10-20T07:07:32Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 1.15.11
this-week-in-past  | [2023-10-20T07:07:37Z INFO  this_week_in_past::scheduler] Begin resource indexing
this-week-in-past  | [2023-10-20T07:07:37Z INFO  this_week_in_past::scheduler] Indexing resources, this may take some time depending on the amount of resources...
this-week-in-past  | [2023-10-20T07:07:37Z INFO  this_week_in_past] 🚀 Launching webserver on http://0.0.0.0:8080 🚀
this-week-in-past  | [2023-10-20T07:07:37Z INFO  actix_server::builder] starting 4 workers
...
```

**Comment by RouHim** [comment]
Currently not, beside debugging, but good idea to improve the logging. I'll implement this, and will get back to you.

**Comment by hajo62** [comment]
F.Y.I.: Again saw an image taken 4 days ago: Image from 19.10. shown on 23.10.
![image](https://github.com/RouHim/this-week-in-past/assets/15800980/df1ca9d8-589b-48e3-83d1-6f1e15b2d20e)

**Comment by hajo62** [comment]
F.Y.I.: Strange enough; yesterday - the second day, the container was running - it seems to show the correct interval. Today - day three - the restarted caused by an error and again, wrong images displayed.
```
this-week-in-past  | [2023-10-25T00:04:06Z INFO  this_week_in_past::scheduler] Cleanup database
this-week-in-past  | thread '<unnamed>' panicked at src/resource_store.rs:19:26:
this-week-in-past  | Vacuum failed: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
this-week-in-past  | stack backtrace:
this-week-in-past  |    0:           0x71394c - <unknown>
this-week-in-past  |    1:           0x5744b4 - <unknown>
this-week-in-past  |    2:           0x6e929c - <unknown>
this-week-in-past  |    3:           0x714b84 - <unknown>
this-week-in-past  |    4:           0x71478c - <unknown>
this-week-in-past  |    5:           0x7156c8 - <unknown>
this-week-in-past  |    6:           0x7151f4 - <unknown>
this-week-in-past  |    7:           0x715168 - <unknown>
this-week-in-past  |    8:           0x71515c - <unknown>
this-week-in-past  |    9:           0x4093a0 - <unknown>
this-week-in-past  |   10:           0x4096c4 - <unknown>
this-week-in-past  |   11:           0x501e78 - <unknown>
this-week-in-past  |   12:           0x5051a0 - <unknown>
this-week-in-past  |   13:           0x504190 - <unknown>
this-week-in-past  |   14:           0x479e90 - <unknown>
this-week-in-past  |   15:           0x4818bc - <unknown>
this-week-in-past  |   16:           0x716774 - <unknown>
this-week-in-past  | [2023-10-25T00:04:21Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 1.16.0

```

**Comment by RouHim** [comment]
Unfortunately, I really can't explain it, from the code I only compare the whole date without considering the time. I also do not manage to reproduce it with my data. 

I have now improved the logging so that in the debug log the current image is output to the console, so it may be possible for you to send me a "broken" image.

**Comment by hajo62** [comment]
Just pulled, but logs shows `1.16.1`?!

**Comment by RouHim** [comment]
Just a moment the software is still building...

**Comment by RouHim** [comment]
If this pipeline is green, you should be able to pull 1.16.3

https://github.com/RouHim/this-week-in-past/actions/runs/6683028611

**Comment by hajo62** [comment]
> in the debug log the current image is output to the console

Hhm, the log does not show the displayed image and the browsers developer console neither (Tried firefox and chrome)?! - Would I need to set a debug environment variable? - I just have the `RUST_BACKTRACE: full` in compose-file.

<img width="403" alt="image" src="https://github.com/RouHim/this-week-in-past/assets/15800980/7e7ed9cb-d6ed-444f-ab36-1e62fa66b1c2">

**Comment by RouHim** [comment]
It is in the log of the container

**Comment by hajo62** [comment]
`docker-compose logs this-week-in-past`
```
this-week-in-past  | [2023-10-29T11:30:21Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 1.16.3
this-week-in-past  | [2023-10-29T11:30:27Z INFO  this_week_in_past::scheduler] Begin resource indexing
this-week-in-past  | [2023-10-29T11:30:27Z INFO  this_week_in_past] 🚀 Launching webserver on http://0.0.0.0:8080 🚀
this-week-in-past  | [2023-10-29T11:30:27Z INFO  this_week_in_past::scheduler] Indexing resources, this may take some time depending on the amount of resources...
this-week-in-past  | [2023-10-29T11:30:27Z INFO  actix_server::builder] starting 4 workers
this-week-in-past  | [2023-10-29T11:30:27Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
this-week-in-past  | [2023-10-29T11:30:27Z INFO  this_week_in_past::filesystem_client] Skipping folder: "/resources/2010-2019/2013/2013.02 Söll" because it contains a .ignore file
...
this-week-in-past  | [2023-10-29T11:33:33Z INFO  this_week_in_past::scheduler] Found 25417 resources
this-week-in-past  | [2023-10-29T11:33:33Z INFO  this_week_in_past::scheduler] Purging resources store
this-week-in-past  | [2023-10-29T11:33:33Z INFO  this_week_in_past::scheduler] Cleanup cache
this-week-in-past  | [2023-10-29T11:33:33Z INFO  this_week_in_past::scheduler] Inserting new resources
this-week-in-past  | [2023-10-29T11:33:40Z INFO  this_week_in_past::scheduler] Cleanup database
this-week-in-past  | [2023-10-29T11:33:43Z INFO  this_week_in_past::scheduler] Job done in 196.06272454s!
```

**Comment by RouHim** [comment]
When you now visit the web address, you should see a debug entry in the log. If this is not the case, you should see a a debug entry like this:
```
[2023-10-29T16:23:51Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "0caaa1fb9b5100b010a8a78f5c09e35e", path: "/resources/Photos from 2017/20171031_163155.jpg", content_type: "image/jpeg", name: "20171031_163155.jpg", content_length: 592358, last_modified: 2022-03-10T04:41:30, taken: Some(2017-10-31T16:31:55), location: Some(GeoLocation { latitude: 50.36972, longitude: 7.5133333 }), orientation: Some(ImageOrientation { rotation: 270, mirror_vertically: false }) }
```

**Comment by hajo62** [comment]
Yesterday all went fine, but right now, I saw an photo taken on 27.10. (today: 31.10.)
![image](https://github.com/RouHim/this-week-in-past/assets/15800980/ec9eebee-4fcf-46cc-8ef7-1ec0cd9e3129)
log entry:
```
this-week-in-past  | [2023-10-31T07:21:24Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "e58e3fcbc0ff6b6904e9501b4307e238", path: "/resources/1990-1999/1998/1998.10 - Sulawesi/dia266.jpg", content_type: "image/jpeg", name: "dia266.jpg", content_length: 3290866, last_modified: 1998-10-27T11:35:00, taken: Some(1998-10-27T12:35:00), location: Some(GeoLocation { latitude: 1.4766362, longitude: 124.83736 }), orientation: None }
```
Link to that photo: https://nc.hajo62.duckdns.org/s/oJax7FFBNQkdPq9

**Comment by RouHim** [comment]
Thanks, I will look into it. Btw the font looks terrible, I should define a standard instead of relying on the system fonts.

**Comment by hajo62** [comment]
> Btw the font looks terrible

It's firefox on a Mac. In chrome it's slightly better, but seems to be different for date and weather.
<img width="697" alt="image" src="https://github.com/RouHim/this-week-in-past/assets/15800980/026b9f5a-9000-430c-8455-2155033b1237">

And that's in Home Assistant: 
![image](https://github.com/RouHim/this-week-in-past/assets/15800980/aba90657-d041-4e65-ae6f-030ea8c70039)
Might you share your Dashboard code for the embedded slide show?

**Comment by RouHim** [comment]
I use a Iframe:
```
  - title: Tablet
    path: tablet
    type: sidebar
    badges: []
    cards:
      - type: iframe
        url: http://192.168.0.5:12556
        aspect_ratio: 120%
```

I quickly threw the image in at my server, and it is not displayed because it is older than 3 days. The only thing that remains is that the current time is probably wrong on your server. I have installed a log message that displays the current server time.

As always, it is live when this pipeline is done:
https://github.com/RouHim/this-week-in-past/actions/runs/6703508281

**Comment by hajo62** [comment]
I don't think, it the images. 
Meanwhile had three taken on 27.10.

**Comment by hajo62** [comment]
> current time is probably wrong on your server

```
𝜋  ~ date
Tue Oct 31 08:47:44 CET 2023
```

**Comment by RouHim** [comment]
The log should now contain the system time and the database after this is done:
https://github.com/RouHim/this-week-in-past/actions/runs/6703655593

Last thing that comes on my mind.

**Comment by hajo62** [comment]
```
this-week-in-past  | [2023-10-31T08:03:46Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 1.17.0
this-week-in-past  | [2023-10-31T08:03:46Z INFO  this_week_in_past] 📅 System time: 2023-10-31 08:03:46
```

**Comment by RouHim** [comment]
Please check again, there should now an additional entry for the database.

**Comment by hajo62** [comment]
```
this-week-in-past  | [2023-10-31T08:28:18Z INFO  this_week_in_past] 👋 Welcome to this-week-in-past version 1.17.1
this-week-in-past  | [2023-10-31T08:28:18Z INFO  this_week_in_past] 📅 System time: 2023-10-31 08:28:18
this-week-in-past  | [2023-10-31T08:28:19Z INFO  this_week_in_past] 📅 Database time: 2023-10-31 08:28:19
this-week-in-past  | [2023-10-31T08:28:19Z INFO  this_week_in_past::scheduler] Begin resource indexing
```

**Comment by hajo62** [comment]
I did some greps on the logs.
Not sure if it helps: 
Today 01.11, i saw some images from 10-28. Then suddenly the first image from 11-04 appeared and since then now more images from 10-28.

In short: I saw _to old_ images, till the first image if the right interval end was shown...

```
docker-compose logs this-week-in-past | grep -e "Some(.........4T........)" -e "Some(.........8T........)" | cut -d "," -f1,7
this-week-in-past  | [2023-11-01T02:11:34Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "3d4f744fc33dc093924262bd0d691bcb", taken: Some(1986-10-28T12:05:00)
this-week-in-past  | [2023-11-01T09:29:22Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "ee204b4c37465d80ad78339811169c8e", taken: Some(1986-10-28T12:40:00)
this-week-in-past  | [2023-11-01T09:37:37Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "22fcb0ceb866c03756494a01bc12c964", taken: Some(2018-10-28T14:41:21)
this-week-in-past  | [2023-11-01T09:39:41Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "16a1167fea0e6ed4c841515dd6b64fa1", taken: Some(2018-10-28T14:41:31)
this-week-in-past  | [2023-11-01T09:47:48Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "3181022475eb7cd9a1ed47c763cef68f", taken: Some(1998-10-28T12:40:00)
this-week-in-past  | [2023-11-01T09:57:52Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "e0bce25ddd844369d386460f83fdac5e", taken: Some(1986-10-28T12:30:00)
this-week-in-past  | [2023-11-01T10:03:52Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "6e4af870fa675563e6a6c84b5edeb928", taken: Some(1986-10-28T12:45:00)
this-week-in-past  | [2023-11-01T10:19:37Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "6d22c003000187476de5321152f41e26", taken: Some(2021-11-04T14:12:43)
this-week-in-past  | [2023-11-01T10:51:11Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "ff9a180ccdf8684906802e46b003d791", taken: Some(2021-11-04T13:33:49)
this-week-in-past  | [2023-11-01T10:55:14Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "d38f6b68b2023d85ad98c771dc1d5e17", taken: Some(2021-11-04T15:39:17)
this-week-in-past  | [2023-11-01T10:57:19Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "7e26daf78cc188dd4888a35cb6147d56", taken: Some(2021-11-04T14:12:20)
this-week-in-past  | [2023-11-01T11:03:28Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "9c1a3ce7fa30d9d5f5f209330816b96e", taken: Some(2021-11-04T17:36:54)
this-week-in-past  | [2023-11-01T11:05:31Z DEBUG this_week_in_past::resource_endpoint] Resource: ImageResource { id: "a5654eba23e6dbebe5faebdad6bd975b", taken: Some(2021-11-04T18:40:20)

**Comment by hajo62** [comment]
Updated my _grep_ command a bit:
```
docker-compose logs this-week-in-past | sed -e 's/Z DEBUG.*path:/] |/g' -e 's/, content_type.*taken: / | taken: /g' -e 's/, location.*//g' | awk -F '|' '{print $1,$2,$4,$3}' | grep -e "........13T" -e "........20T"
```

**Comment by RouHim** [comment]
Difficult, I've tried to reproduce the whole situation over several days and unfortunately I can't figure it out. 
The only other thing that came to my mind is that reindexing starts exactly at midnight, maybe I'll move it back a bit so that there's no overlap with the previous day if the clocks are slightly different.

**Comment by hajo62** [comment]
Really a strange thing. For my environment it seems to be reproducible every day.
I do not assume, that (re)indexing causes this behaviour.
Today, the switching happened sometime from 9:11 to 9:47 
Might there be something like a queue or cache?

During the night, when my laptop is sleeping, only a few images seem to be _displayed_. The switching is 1 to 2 hours after I've awakened the Laptop - updating every 2 mins.

**Comment by hajo62** [comment]
First day with 1.18.5 looks good.

**Comment by RouHim** [comment]
Ok, let's test it some more days...

**Comment by hajo62** [comment]
Unfortunately:
```
[2023-11-19T00:51:17]   taken: Some(2016-11-15T12:21:10)
[2023-11-19T08:48:54]   taken: Some(2016-11-15T12:21:08)
[2023-11-19T09:00:54]   taken: Some(2016-11-15T10:33:02)
[2023-11-19T09:08:54]   taken: Some(2016-11-15T12:49:57)
[2023-11-19T09:12:54]   taken: Some(2016-11-15T11:14:28)
[2023-11-19T09:14:54]   taken: Some(2018-11-15T11:02:26)
[2023-11-19T09:20:54]   taken: Some(2016-11-15T11:16:33)
[2023-11-19T09:24:54]   taken: Some(2016-11-15T10:33:16)
[2023-11-19T09:32:54]   taken: Some(2018-11-15T10:45:49)
[2023-11-19T09:34:54]   taken: Some(2016-11-15T11:18:15)
```

**Comment by RouHim** [comment]
Ok now I realize what else it could be. The REFRESH_INTERVAL is set to 3 hours by default, which means that in the worst case the daily updated images are only retrieved 3 hours after opening the browser. Reduce the value to "60" perhaps this will work better.

**Comment by hajo62** [comment]
Yesterday and Today both days one _wrong_ image in the first hour after a woke up my laptop, which is the expected (old images in the first hour or less) behaviour?
```
[2023-11-21T07:06:49]   taken: Some(2004-11-17T12:44:42)
[2023-11-21T07:50:49]   taken: Some(2022-11-24T13:11:24)
```
Is it easy to explain, why the refresh changes the shown images? - The app takes a whole list of images from the database an goes through?

**Comment by RouHim** [comment]
Yes, exactly. So when waking up, you should definitely refresh the browser.
